    dc.l    loc_00011AE4-0
    dc.l    loc_00011AF6-0
    dc.l    loc_00011B08-0
    dc.l    loc_00011B1A-0
    dc.l    loc_00011B2C-0
    dc.l    loc_00011B3E-0
    dc.l    loc_00011B50-0
    dc.l    loc_00011B62-0
    dc.l    loc_00011B74-0
    dc.l    loc_00011B86-0
loc_00011AE4:
    dc.b    $00
    dc.b    $02
    dc.b    $FF
    dc.b    $F8
    dc.b    $0D
    dc.b    $02
    dc.b    $E4
    dc.b    $90
    dc.b    $FF
    dc.b    $EC
    dc.b    $FF
    dc.b    $F8
    dc.b    $01
    dc.b    $02
    dc.b    $E4
    dc.b    $98
    dc.b    $00
    dc.b    $0C
loc_00011AF6:
    dc.b    $00
    dc.b    $02
    dc.b    $FF
    dc.b    $F8
    dc.b    $0D
    dc.b    $02
    dc.b    $E4
    dc.b    $9A
    dc.b    $FF
    dc.b    $EC
    dc.b    $FF
    dc.b    $F8
    dc.b    $01
    dc.b    $02
    dc.b    $E4
    dc.b    $A2
    dc.b    $00
    dc.b    $0C
loc_00011B08:
    dc.b    $00
    dc.b    $02
    dc.b    $FF
    dc.b    $F8
    dc.b    $0D
    dc.b    $02
    dc.b    $E4
    dc.b    $A4
    dc.b    $FF
    dc.b    $EC
    dc.b    $FF
    dc.b    $F8
    dc.b    $01
    dc.b    $02
    dc.b    $E4
    dc.b    $AC
    dc.b    $00
    dc.b    $0C
loc_00011B1A:
    dc.b    $00
    dc.b    $02
    dc.b    $FF
    dc.b    $F8
    dc.b    $0D
    dc.b    $02
    dc.b    $E4
    dc.b    $AE
    dc.b    $FF
    dc.b    $EC
    dc.b    $FF
    dc.b    $F8
    dc.b    $01
    dc.b    $02
    dc.b    $E4
    dc.b    $B6
    dc.b    $00
    dc.b    $0C
loc_00011B2C:
    dc.b    $00
    dc.b    $02
    dc.b    $FF
    dc.b    $F8
    dc.b    $0D
    dc.b    $02
    dc.b    $E4
    dc.b    $B8
    dc.b    $FF
    dc.b    $EC
    dc.b    $FF
    dc.b    $F8
    dc.b    $01
    dc.b    $02
    dc.b    $E4
    dc.b    $C0
    dc.b    $00
    dc.b    $0C
loc_00011B3E:
    dc.b    $00
    dc.b    $02
    dc.b    $FF
    dc.b    $F8
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $C2
    dc.b    $FF
    dc.b    $EE
    dc.b    $FF
    dc.b    $F8
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $C6
    dc.b    $00
    dc.b    $02
loc_00011B50:
    dc.b    $00
    dc.b    $02
    dc.b    $FF
    dc.b    $F8
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $C6
    dc.b    $FF
    dc.b    $EE
    dc.b    $FF
    dc.b    $F8
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $CA
    dc.b    $00
    dc.b    $02
loc_00011B62:
    dc.b    $00
    dc.b    $02
    dc.b    $FF
    dc.b    $F8
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $CE
    dc.b    $FF
    dc.b    $EE
    dc.b    $FF
    dc.b    $F8
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $D2
    dc.b    $00
    dc.b    $02
loc_00011B74:
    dc.b    $00
    dc.b    $02
    dc.b    $FF
    dc.b    $F8
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $D2
    dc.b    $FF
    dc.b    $EE
    dc.b    $FF
    dc.b    $F8
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $CA
    dc.b    $00
    dc.b    $02
loc_00011B86:
    dc.b    $00
    dc.b    $02
    dc.b    $FF
    dc.b    $F8
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $C2
    dc.b    $FF
    dc.b    $EE
    dc.b    $FF
    dc.b    $F8
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $D2
    dc.b    $00
    dc.b    $02