    dc.l    loc_00012D38-0
    dc.l    loc_00012D38-0
    dc.l    loc_00012D62-0
    dc.l    loc_00012D84-0
    dc.l    loc_00012DAE-0
    dc.l    loc_00012DD0-0
    dc.l    loc_00012DDA-0
loc_00012D38:
    dc.b    $00
    dc.b    $05
    dc.b    $FF
    dc.b    $E0
    dc.b    $07
    dc.b    $01
    dc.b    $84
    dc.b    $00
    dc.b    $FF
    dc.b    $E0
    dc.b    $FF
    dc.b    $C8
    dc.b    $0D
    dc.b    $01
    dc.b    $84
    dc.b    $08
    dc.b    $FF
    dc.b    $F0
    dc.b    $FF
    dc.b    $F0
    dc.b    $0D
    dc.b    $01
    dc.b    $84
    dc.b    $1C
    dc.b    $FF
    dc.b    $F0
    dc.b    $FF
    dc.b    $C8
    dc.b    $0B
    dc.b    $01
    dc.b    $84
    dc.b    $24
    dc.b    $00
    dc.b    $10
    dc.b    $FF
    dc.b    $E8
    dc.b    $0E
    dc.b    $01
    dc.b    $84
    dc.b    $30
    dc.b    $00
    dc.b    $10
loc_00012D62:
    dc.b    $00
    dc.b    $04
    dc.b    $FF
    dc.b    $C8
    dc.b    $0F
    dc.b    $01
    dc.b    $84
    dc.b    $3C
    dc.b    $FF
    dc.b    $E8
    dc.b    $FF
    dc.b    $C8
    dc.b    $0F
    dc.b    $01
    dc.b    $84
    dc.b    $4C
    dc.b    $00
    dc.b    $08
    dc.b    $FF
    dc.b    $E8
    dc.b    $0E
    dc.b    $01
    dc.b    $84
    dc.b    $94
    dc.b    $FF
    dc.b    $E0
    dc.b    $FF
    dc.b    $E8
    dc.b    $0E
    dc.b    $01
    dc.b    $84
    dc.b    $A0
    dc.b    $00
    dc.b    $00
loc_00012D84:
    dc.b    $00
    dc.b    $05
    dc.b    $FF
    dc.b    $C8
    dc.b    $0F
    dc.b    $01
    dc.b    $84
    dc.b    $5C
    dc.b    $FF
    dc.b    $E0
    dc.b    $FF
    dc.b    $C8
    dc.b    $0B
    dc.b    $01
    dc.b    $84
    dc.b    $6C
    dc.b    $00
    dc.b    $00
    dc.b    $FF
    dc.b    $F0
    dc.b    $01
    dc.b    $01
    dc.b    $84
    dc.b    $AC
    dc.b    $FF
    dc.b    $D8
    dc.b    $FF
    dc.b    $E8
    dc.b    $0E
    dc.b    $01
    dc.b    $84
    dc.b    $AE
    dc.b    $FF
    dc.b    $E0
    dc.b    $FF
    dc.b    $E8
    dc.b    $0E
    dc.b    $01
    dc.b    $84
    dc.b    $BA
    dc.b    $00
    dc.b    $00
loc_00012DAE:
    dc.b    $00
    dc.b    $04
    dc.b    $FF
    dc.b    $C8
    dc.b    $0F
    dc.b    $01
    dc.b    $84
    dc.b    $78
    dc.b    $FF
    dc.b    $E0
    dc.b    $FF
    dc.b    $C8
    dc.b    $0B
    dc.b    $01
    dc.b    $84
    dc.b    $88
    dc.b    $00
    dc.b    $00
    dc.b    $FF
    dc.b    $E8
    dc.b    $0E
    dc.b    $01
    dc.b    $84
    dc.b    $C6
    dc.b    $FF
    dc.b    $E0
    dc.b    $FF
    dc.b    $E8
    dc.b    $0A
    dc.b    $01
    dc.b    $84
    dc.b    $D2
    dc.b    $00
    dc.b    $00
loc_00012DD0:
    dc.b    $00
    dc.b    $01
    dc.b    $FF
    dc.b    $D8
    dc.b    $0E
    dc.b    $01
    dc.b    $84
    dc.b    $10
    dc.b    $FF
    dc.b    $F0
loc_00012DDA:
    dc.b    $00
    dc.b    $01
    dc.b    $FF
    dc.b    $D8
    dc.b    $0E
    dc.b    $01
    dc.b    $84
    dc.b    $DB
    dc.b    $FF
    dc.b    $F0