    dc.l    loc_000118B6-0
    dc.l    loc_000118D0-0
    dc.l    loc_000118EA-0
    dc.l    loc_0001191C-0
    dc.l    loc_0001194E-0
    dc.l    loc_00011980-0
loc_000118B6:
    dc.b    $00
    dc.b    $03
    dc.b    $FF
    dc.b    $E4
    dc.b    $06
    dc.b    $00
    dc.b    $A4
    dc.b    $C0
    dc.b    $FF
    dc.b    $F0
    dc.b    $FF
    dc.b    $E4
    dc.b    $06
    dc.b    $00
    dc.b    $AC
    dc.b    $C0
    dc.b    $00
    dc.b    $00
    dc.b    $FF
    dc.b    $D8
    dc.b    $04
    dc.b    $00
    dc.b    $E4
    dc.b    $CC
    dc.b    $FF
    dc.b    $F8
loc_000118D0:
    dc.b    $00
    dc.b    $03
    dc.b    $FF
    dc.b    $E4
    dc.b    $06
    dc.b    $00
    dc.b    $A4
    dc.b    $C6
    dc.b    $FF
    dc.b    $F0
    dc.b    $FF
    dc.b    $E4
    dc.b    $06
    dc.b    $00
    dc.b    $AC
    dc.b    $C6
    dc.b    $00
    dc.b    $00
    dc.b    $FF
    dc.b    $D8
    dc.b    $04
    dc.b    $00
    dc.b    $E4
    dc.b    $CE
    dc.b    $FF
    dc.b    $F8
loc_000118EA:
    dc.b    $00
    dc.b    $06
    dc.b    $FF
    dc.b    $E3
    dc.b    $05
    dc.b    $03
    dc.b    $E4
    dc.b    $FC
    dc.b    $FF
    dc.b    $F8
    dc.b    $FF
    dc.b    $F0
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $F4
    dc.b    $FF
    dc.b    $F8
    dc.b    $FF
    dc.b    $E4
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $EC
    dc.b    $FF
    dc.b    $E8
    dc.b    $FF
    dc.b    $E4
    dc.b    $05
    dc.b    $02
    dc.b    $EC
    dc.b    $EC
    dc.b    $00
    dc.b    $08
    dc.b    $FF
    dc.b    $DC
    dc.b    $02
    dc.b    $01
    dc.b    $E4
    dc.b    $E6
    dc.b    $FF
    dc.b    $FC
    dc.b    $FF
    dc.b    $C5
    dc.b    $0F
    dc.b    $00
    dc.b    $E4
    dc.b    $D0
    dc.b    $FF
    dc.b    $F0
loc_0001191C:
    dc.b    $00
    dc.b    $06
    dc.b    $FF
    dc.b    $E3
    dc.b    $05
    dc.b    $03
    dc.b    $E4
    dc.b    $FC
    dc.b    $FF
    dc.b    $F8
    dc.b    $FF
    dc.b    $F0
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $F4
    dc.b    $FF
    dc.b    $F8
    dc.b    $FF
    dc.b    $E4
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $F0
    dc.b    $FF
    dc.b    $E8
    dc.b    $FF
    dc.b    $E4
    dc.b    $05
    dc.b    $02
    dc.b    $EC
    dc.b    $EC
    dc.b    $00
    dc.b    $08
    dc.b    $FF
    dc.b    $DC
    dc.b    $06
    dc.b    $01
    dc.b    $E4
    dc.b    $E0
    dc.b    $FF
    dc.b    $F8
    dc.b    $FF
    dc.b    $C5
    dc.b    $0F
    dc.b    $00
    dc.b    $E4
    dc.b    $D0
    dc.b    $FF
    dc.b    $E8
loc_0001194E:
    dc.b    $00
    dc.b    $06
    dc.b    $FF
    dc.b    $E3
    dc.b    $05
    dc.b    $03
    dc.b    $E4
    dc.b    $FC
    dc.b    $FF
    dc.b    $F8
    dc.b    $FF
    dc.b    $F0
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $F8
    dc.b    $FF
    dc.b    $F8
    dc.b    $FF
    dc.b    $E4
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $EC
    dc.b    $FF
    dc.b    $E8
    dc.b    $FF
    dc.b    $E4
    dc.b    $05
    dc.b    $02
    dc.b    $EC
    dc.b    $EC
    dc.b    $00
    dc.b    $08
    dc.b    $FF
    dc.b    $DC
    dc.b    $02
    dc.b    $01
    dc.b    $E4
    dc.b    $E9
    dc.b    $FF
    dc.b    $FC
    dc.b    $FF
    dc.b    $C9
    dc.b    $0F
    dc.b    $00
    dc.b    $E4
    dc.b    $D0
    dc.b    $FF
    dc.b    $F0
loc_00011980:
    dc.b    $00
    dc.b    $06
    dc.b    $FF
    dc.b    $E3
    dc.b    $05
    dc.b    $03
    dc.b    $E4
    dc.b    $FC
    dc.b    $FF
    dc.b    $F8
    dc.b    $FF
    dc.b    $F0
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $F4
    dc.b    $FF
    dc.b    $F8
    dc.b    $FF
    dc.b    $E4
    dc.b    $05
    dc.b    $02
    dc.b    $E4
    dc.b    $EC
    dc.b    $FF
    dc.b    $E8
    dc.b    $FF
    dc.b    $E4
    dc.b    $05
    dc.b    $02
    dc.b    $EC
    dc.b    $F0
    dc.b    $00
    dc.b    $08
    dc.b    $FF
    dc.b    $DC
    dc.b    $06
    dc.b    $01
    dc.b    $EC
    dc.b    $E0
    dc.b    $FF
    dc.b    $F8
    dc.b    $FF
    dc.b    $C7
    dc.b    $0F
    dc.b    $00
    dc.b    $E4
    dc.b    $D0
    dc.b    $FF
    dc.b    $F8
